### ISSUE TITLE
Unexpected Directory Change After Running ./build.sh Script

### ISSUE THREAD

**Issue by AmirAlmasi** [me6ran/simple_state_machine_with_cmake#7]
After executing the `./build.sh` script, the user's current directory changes to another location. This behavior seems a bit unusual. Ideally, as a user running a script, I would expect to return to the same directory where I was before executing the script. 
To address this concern, you have two options: either change the directory and then return to the user's initial location, or run CMake with specific options without changing the directory.

**Comment by me6ran** [comment]
I was trying to duplicate the issue on MacOS and Debian was not successful. looks like the changing directory is local within the script, but to have a deterministic way I found some Cmake options that can be used to specify the build and source directory. changes has been pushed to the same PR. please take a look to confirm if these are the option you were mentioning.
